### ISSUE TITLE
dbms_metadata.get_ddl does not work when used in UTL_GENERATE_ORADEW

### ISSUE THREAD

**Issue by Danieleeee** [mickeypearce/oradew-vscode#51]
I'm using the custom **UTL_GENERATE_ORADEW** package, the procedure is the one you proposed **_getDdl_**.
If I try to import the definition of tables or triggers, I get the following error, given by the procedure _**dbms_metadata.get_ddl**_:

```
ORA-31603: "TABLE_NAME" object of type TABLE not found in the "SCHEMA_NAME" schema
ORA-06512: a "SYS.DBMS_METADATA", line 6478
ORA-06512: a "SYS.DBMS_SYS_ERROR", line 105
ORA-06512: a "SYS.DBMS_METADATA", line 6465
ORA-06512: a "SYS.DBMS_METADATA", line 9202
ORA-06512: a "SIU.UTL_GENERATE_ORADEW", line 726
```

**Comment by Danieleeee** [comment]
I am using the package proposed in oradew-generators:
[UTL_GENERATE.sql](https://github.com/mickeypearce/oradew-generators/blob/master/src/PACKAGE_BODIES/UTL_GENERATE.sql)

**Comment by mickeypearce** [comment]
Hey @Danieleeee ,

I am not sure where the problem is therefore I kindly invite you to contribute. you can open a PR I will gladly review it and provide with assistance in case you will need some help. 

 If there is a problem with `UTL_GENERATE.sql` please open a PR in `oradew-generators` repository. Thanks.

**Comment by Danieleeee** [comment]
I solved the problem adding AUTHID CURRENT_USER:
`CREATE OR REPLACE PACKAGE UTL_GENERATE_ORADEW AUTHID CURRENT_USER`
