### ISSUE TITLE
problems connecting to oracle database (proxy authentication)

### ISSUE THREAD

**Issue by nivekus82** [mickeypearce/oradew-vscode#77]
hello everyone,

im working with vsc and python since a few weeks. stept by step i´m adding new packages to vsc and now i try to run oradew. it would be perfect for my daily developing. 

i installed the package and initialized the workspace. now i try to config the file dbconfig.json. after doing this i run the command "Create source from db". unfortunatley that doesn´t work.

following line is in the dbconfig.json:

{"DEV":{connectString":"name in tnsnames", "users":[{"user":"user_name", "password":"user_password", "schemas": "user_schema"})}}

the command runs, no exception, but no DB-Object ist in the file-explorer, all directories  src, scripts, test are empty

i tried a long time in many versions, but no success

any help is welcome :-)

**Comment by nivekus82** [comment]
i just tried  another way that works. i have an older database where the test succeded. the only difference is the authentification  method. on my prod db i have to login per proxy user, on my older db  per "normal" user.

is there any way to use the tool per proxy user login like user_name[proxy_user]

**Comment by mickeypearce** [comment]
Hello,

I've never used proxy users, but it looks like oracle-nodedb supports proxy connections:

https://node-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#pool-proxy-authentication

If it is of any help to you here is the oradew code for connections:
https://github.com/mickeypearce/oradew-vscode/blob/63727842aebfa67253d0d5f50b1d37514881a3a1/src/cli/common/db.ts#L39

Feel free to open a PR if you feel like it ....

**Comment by carnifex82** [comment]
Only fixing this query wouldn't help. Apparently the issue is not the connection, but getting the correct objects - because oradew sees the owner equal to the user. 

For a proxy auth you submit the username as following: proxy_user[session_user]. The objects that you access this way, are owned by the session_user.  So in case of a proxy auth, oradew needs to either add a parameter in dbconfig.json and deal with it accordingly (extracting the owner from the user-string)

Or maybe easier: just plainly do it anytime when there are "[somestring]" detected in the username. There shouldn't be any side effects, since the square brackets are not valid characters in an oracle username ([see ](https://docs.oracle.com/cd/A81042_01/DOC/server.816/a76989/ch29.htm))

**Comment by mickeypearce** [comment]
Does your `dbconfig.json` looks something like the following example when you successfully conected ? Because `schemas` is intented for this puropse when you need to get objects for different user than you the user for connection but it wasn't tested with proxy user.

```json
{
  "DEV": {
    "connectString": "name in tnsnames",
    "users": [
      {
        "user": "proxy_user[session_user]",
        "password": "user_password",
        "schemas": "session_user"
      }
    ]
  }
}
```

**Comment by nivekus82** [comment]
Sorry for my late answer. Thanks for your response, now it works just as expected. As you can see in my first post, i already tried the parameter "schemas", but i didn´t leave the sessionuser in square brackets behind the proxyuser in the user parameter.

Thanks, @mickeypearce and  @carnifex82 , i appreciate your help

**Comment by mickeypearce** [comment]
Awesome, I didn't expect it to work out-of-the-box ...
